### ISSUE TITLE
submodule problem

### ISSUE THREAD

**Issue by clearloveu** [sns3/sns3-satellite#10]
Hi！When I follow the README steps to execute ‘git submodule update --init --recursive’ ，my computer is stuck in “Submodule 'data' (https://forge.net4sat.org/sns3-data/sns-3-scenarios.git) registered for path 'data'
Cloning into 'C:/Users/asus/Desktop/satellite/data'...  ” .  I try it many time but still failed , can you give me a help? Thank you !

**Comment by pravenea-cnes** [comment]
Hello,
I don't know why your computer is stuck at this step.
From your description, I guess you are using Windows.
I haven't tried the install process on Windows.

As far as I know, NS-3 and SNS3 can only run on Linux.
Can you confirm that your computer OS is Windows ?
If the answer is yes, I would advise to try the install process on a Linux machine.

**Comment by clearloveu** [comment]
Hi！
 I firstly tried this operation on Ubuntu 18.04, and I encountered this problem. The problem above is that I simulate git operations under Windows. I tried 'git submodule update --init --recursive' on Linux systems on different machines and failed. Does it make a big difference if it's not installed? 
![capture](https://user-images.githubusercontent.com/43346562/56295608-a0425580-615f-11e9-9068-1360cc2c8af5.PNG)

**Comment by dupejb-cnes** [comment]
Hi,
SNS3 main scenarios will not work with the data submodule. Can you reach the hosting website : https://forge.net4sat.org/sns3-data/sns-3-scenarios? A .zip repo can be downloaded from the website. Beware that this module is very large (around 3GB).

**Comment by naeemk** [comment]
I ack that the link to net4sat seems broken --seems to be a problem on the server side. could you please check and fix it?

**Comment by dupejb-cnes** [comment]
Hi,
We have a scheduled maintainance of net4sat. Should be up soon. 
Please note that this does not prevent from using sns3, only the examples using the data submodule.
