### ISSUE TITLE
error runnin examples in sns3

### ISSUE THREAD

**Issue by audjo** [sns3/sns3-satellite#11]
When I run an example with sns3 always fail with the signal SIGIOT
Please, could you help me?
./waf --run contrib/satellite/examples/sat-tutorial-example
Waf: Entering directory `/home/aurora/workspace2/bake/source/ns-3.29/build'
Waf: Leaving directory `/home/aurora/workspace2/bake/source/ns-3.29/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (6.043s)
assert failed. cond="IsValidDirectory (outputPath)", msg="contrib/satellite/data/sims/example-tutorial/Simple/ is not a valid directory", file=../contrib/satellite/utils/satellite-env-variables.cc, line=223
terminate called without an active exception
Command ['/home/aurora/workspace2/bake/source/ns-3.29/build/contrib/satellite/examples/ns3-dev-sat-tutorial-example-debug'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

**Comment by dupejb-cnes** [comment]
Hello,

It looks like the output path (where statistics and results are written) does not exist :
>  msg="contrib/satellite/data/sims/example-tutorial/Simple/ is not a valid directory"
The ouput path should not have this "Simple" directory. Is the example started with default values?

**Comment by dupejb-cnes** [comment]
Hello,
The data submodule used to point to a non-existing commit, it is now fixed.
