### ISSUE TITLE
satellite network

### ISSUE THREAD

**Issue by clearloveu** [sns3/sns3-satellite#12]
Hello!
I see on your website that sns3's satellite system has a geostationary satellite. Does it have Leo and MEO satellites?

**Comment by dupejb-cnes** [comment]
Hi,
Unfortunately no, sns3 is focused on DVB-S2/RCS2 which is dedicated to GEO transparent satellites. LEO and/or MEO would require orbit propagation models (typ. SGP4).

**Comment by clearloveu** [comment]
I'm sorry to have been bothering you.
Is the orbit propagation models available in sns3?

**Comment by jeanbaptistedupe** [comment]
Hi,
No, there is no such library in sns3. You can however find c++ code of SGP4 models at https://www.danrw.com/sgp4/.
