### ISSUE TITLE
NS_LOG display issue

### ISSUE THREAD

**Issue by Ox7FFFFFFF** [sns3/sns3-satellite#14]
Hello,
I tried to run the "sat-link-budget-example" code like this:
![image](https://user-images.githubusercontent.com/14291479/77659137-a2897280-6fb2-11ea-9d9a-44aa96957f94.png)
BUT, it didn't show any NS_LOG_INFO message.

I had added 'LogComponentEnable("sat-link-budget-example", LOG_LEVEL_INFO);' into the example  code, and also executed the "export NS_LOG=sat-link-budget-example=level_all" at the command line, but it still show nothing.
Is there any method can solve this problem?
Thanks!

**Comment by jeanbaptistedupe** [comment]
Hi,
is this issue specific to this example? Have you tried with core ns3 (eg. wifi) modules?
Cheers,

**Comment by Ox7FFFFFFF** [comment]
Hi,
it's not the issue specific to this example. I had tried the "sat-environmental-variables-example" example code and the first.cc in the NS3 tutorials. But, the problems still exist. :(
The console only shows the "build finished successfully" message

**Comment by Ox7FFFFFFF** [comment]
Oh, I found the solution!
I used waf to build this project. I execute this command to switch to the debug mode and rebuild the project.
`$ ./waf configure --build-profile=debug --enable-examples --enable-tests`
Finally, it shows the NS_LOG_INFO on my console!!!
Thanks for your reply!
