### ISSUE TITLE
Relationship with the NS2 satellite module

### ISSUE THREAD

**Issue by Ray-1997** [sns3/sns3-satellite#15]
Hello! What is the relationship between SNS3 and the satellite module that comes with NS2?  Is SNS3 only focused on DVB-S2/RCS2 which is dedicated to GEO transparent satellites？

**Comment by pravenea-cnes** [comment]
Hello,
Indeed, SNS3 focuses on DVB-S2/RCS2 standard for a GEO transparent satellite context.
