### ISSUE TITLE
A problem about Slotted-Aloha

### ISSUE THREAD

**Issue by sebastianfcs** [sns3/sns3-satellite#16]
Hi~
my question is : when I run the slotted-aloha example:sat-random-access-slotted-aloha-example.cc, why i cannot see the packet sink info when RTN_LINK?

**Comment by sebastianfcs** [comment]
when FWD_LINK, I can see them.

**Comment by pravenea-cnes** [comment]
Hello,

Could you be more specific while explaining the issue ? so that I can reproduce it.

Thanks in advance

**Comment by sebastianfcs** [comment]
I enabled info logs of CbrApplication and PacketSink in this example. When I run it, I can see the ut users sent the packets but cannot find that the gw user received packets in the terminal.

**Comment by pravenea-cnes** [comment]
Thanks for the clarification.
SNS3 does not allow Slotted Aloha to send user-plane traffic, but only control-plane traffic.
You can find this information in the Random Access section of SNS3 documentation available at http://sns3.org/content/doc/satellite-design.html#random-access.
