### ISSUE TITLE
about throughtput of users

### ISSUE THREAD

**Issue by sebastianfcs** [sns3/sns3-satellite#18]
hi~
i configured a scenario : 300 ut users send to a gw user,packet size = 20Bytes using CRDSA. But i find that receiving performance of gw users is not good. So i wanna know the max width of one user can use.
thank you~
`
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/satellite-module.h"
#include "ns3/applications-module.h"
#include "ns3/traffic-module.h"
#include "ns3/ipv4-l3-protocol.h"

using namespace ns3;
NS_LOG_COMPONENT_DEFINE ("sat-random-access-crdsa-seb-test");

int
main (int argc, char *argv[])
{
  uint32_t beamId (1);
  uint32_t endUsersPerUt (10);
  uint32_t utsPerBeam (30);
  uint32_t packetSize (20);
  std::string interval = "0.2s";
  Time simLength (Seconds (61.0));
  Time appSendStartTime (Seconds (0.1));
  Time appSendStopTime (Seconds(10.0));
  Time appReceiveStartTime (Seconds(0.1));
  Time appReceiveStopTime (Seconds(60.0));

  auto sh= CreateObject<SimulationHelper> ("sat-random-access-crdsa-seb-test");           

  // Enable info logs
  LogComponentEnable ("sat-random-access-crdsa-seb-test", LOG_LEVEL_INFO);
  //LogComponentEnable ("SatRandomAccess", LOG_LEVEL_INFO);
  //LogComponentEnable ("SatUtMac", LOG_LEVEL_INFO);
  //LogComponentEnable ("SatPhyRxCarrier", LOG_LEVEL_INFO);
  //LogComponentEnable ("SatInterference", LOG_LEVEL_INFO);
  //LogComponentEnable ("SatBeamScheduler", LOG_LEVEL_INFO);
  LogComponentEnable ("CbrApplication", LOG_LEVEL_INFO);           //changed by seb
  LogComponentEnable ("PacketSink", LOG_LEVEL_INFO);                   //changed by seb

  Config::SetDefault ("ns3::SatHelper::PacketTraceEnabled", BooleanValue (true));

  // Read command line parameters given by user
  CommandLine cmd;
  cmd.AddValue ("endUsersPerUt", "Number of end users per UT", endUsersPerUt);
  cmd.AddValue ("utsPerBeam", "Number of UTs per spot-beam", utsPerBeam);
  cmd.AddValue ("simLength", "Simulation length in seconds", simLength);
  sh->AddDefaultUiArguments (cmd);
  cmd.Parse (argc, argv);

  sh->SetUserCountPerUt (endUsersPerUt);
  sh->SetUtCountPerBeam (utsPerBeam);
  sh->SetSimulationTime (simLength);
  sh->SetBeamSet ({beamId});

  // Configure error model
  SatPhyRxCarrierConf::ErrorModel em (SatPhyRxCarrierConf::EM_AVI);
  Config::SetDefault ("ns3::SatUtHelper::FwdLinkErrorModel", EnumValue (em));
  Config::SetDefault ("ns3::SatGwHelper::RtnLinkErrorModel", EnumValue (em));
  //Config::SetDefault ("ns3::SatUtMac::CrUpdatePeriod", TimeValue(Seconds(10.0)));

  // Enable Random Access with CRDSA
  Config::SetDefault ("ns3::SatBeamHelper::RandomAccessModel",EnumValue (SatEnums::RA_MODEL_CRDSA));

  // Set Random Access interference model
  Config::SetDefault ("ns3::SatBeamHelper::RaInterferenceModel",EnumValue (SatPhyRxCarrierConf::IF_PER_PACKET));

  // Set Random Access collision model
  Config::SetDefault ("ns3::SatBeamHelper::RaCollisionModel",EnumValue (SatPhyRxCarrierConf::RA_COLLISION_CHECK_AGAINST_SINR));

  // Disable periodic control slots
  Config::SetDefault ("ns3::SatBeamScheduler::ControlSlotsEnabled", BooleanValue (false));

  // Set dynamic load control parameters
  Config::SetDefault ("ns3::SatPhyRxCarrierConf::EnableRandomAccessDynamicLoadControl", BooleanValue (false));
  Config::SetDefault ("ns3::SatPhyRxCarrierConf::RandomAccessAverageNormalizedOfferedLoadMeasurementWindowSize", UintegerValue (10));

  // Set random access parameters
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_MaximumUniquePayloadPerBlock", UintegerValue (3));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_MaximumConsecutiveBlockAccessed", UintegerValue (6));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_MinimumIdleBlock", UintegerValue (2));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_BackOffTimeInMilliSeconds", UintegerValue (250));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_BackOffProbability", UintegerValue (10000));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_HighLoadBackOffProbability", UintegerValue (30000));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_NumberOfInstances", UintegerValue (3));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::RaService0_AverageNormalizedOfferedLoadThreshold", DoubleValue (0.5));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DefaultControlRandomizationInterval", TimeValue (MilliSeconds (100)));
  Config::SetDefault ("ns3::SatRandomAccessConf::CrdsaSignalingOverheadInBytes", UintegerValue (5));
  Config::SetDefault ("ns3::SatRandomAccessConf::SlottedAlohaSignalingOverheadInBytes", UintegerValue (3));

  // Disable CRA and DA
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService0_ConstantAssignmentProvided", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService1_ConstantAssignmentProvided", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService2_ConstantAssignmentProvided", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService3_ConstantAssignmentProvided", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService0_RbdcAllowed", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService1_RbdcAllowed", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService2_RbdcAllowed", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService3_RbdcAllowed", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService0_VolumeAllowed", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService1_VolumeAllowed", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService2_VolumeAllowed", BooleanValue (false));
  Config::SetDefault ("ns3::SatLowerLayerServiceConf::DaService3_VolumeAllowed", BooleanValue (false));

  // Creating the reference system. Note, currently the satellite module supports
  // only one reference system, which is named as "Scenario72". The string is utilized
  // in mapping the scenario to the needed reference system configuration files. Arbitrary
  // scenario name results in fatal error.
 Ptr<SatHelper> helper = sh->CreateSatScenario ();

  // Get the end users so that it is possible to attach applications on them
  NodeContainer utUsers = helper->GetUtUsers ();
  NodeContainer gwUsers = helper->GetGwUsers ();

  ApplicationContainer gwUsersApps;
  ApplicationContainer utUsersApps;

  //---- Start CBR application definitions
  uint16_t port = 9;
  Time startDelay = appSendStartTime;   

  uint32_t GwUserId (0);

  // create application on UT user
  PacketSinkHelper cbrSinkHelper ("ns3::UdpSocketFactory", InetSocketAddress (helper->GetUserAddress (gwUsers.Get (GwUserId)), port));
  CbrHelper cbrHelper ("ns3::UdpSocketFactory", InetSocketAddress (helper->GetUserAddress (gwUsers.Get (GwUserId)), port));
  cbrHelper.SetAttribute ("Interval", StringValue (interval));
  cbrHelper.SetAttribute ("PacketSize", UintegerValue (packetSize));

  // Set destination addresses
  InetSocketAddress cbrDest (helper->GetUserAddress (gwUsers.Get (GwUserId)), port);
  //uint8_t cbrTos (0xB8);
  //cbrDest.SetTos (cbrTos);

  // Cbr and Sink applications creation. CBR to UT users and sinks to GW users.
  gwUsersApps.Add (cbrSinkHelper.Install (gwUsers.Get (GwUserId)));
  gwUsersApps.Get (0)->SetStartTime (appReceiveStartTime);
  gwUsersApps.Get (0)->SetStopTime (appReceiveStopTime);

  for ( uint32_t i = 0; i < utUsers.GetN (); i++)
    {
      cbrHelper.SetAttribute ("Remote", AddressValue (Address (cbrDest)));
      cbrSinkHelper.SetAttribute ("Local", AddressValue (Address (cbrDest)));

      utUsersApps.Add (cbrHelper.Install (utUsers.Get (i)));

      startDelay += Seconds (0.001);      // the start time of each users apps needs a jitter, changed by seb

      // Set start and end times
      utUsersApps.Get (i)->SetStartTime (startDelay);
      utUsersApps.Get (i)->SetStopTime (appSendStopTime);
    }
  //---- Stop CBR application definitions

  NS_LOG_INFO ("--- Cbr-user-defined-example ---");
  NS_LOG_INFO ("  Packet size in bytes: " << packetSize);
  NS_LOG_INFO ("  Packet sending interval: " << interval);
  NS_LOG_INFO ("  Simulation length: " << simLength.GetSeconds ());
  NS_LOG_INFO ("  Number of UTs: " << utsPerBeam);
  NS_LOG_INFO ("  Number of end users per UT: " << endUsersPerUt);

  NS_LOG_INFO ("  ");

  sh->RunSimulation ();

  // check throughput!   changed by seb!
  Ptr<PacketSink> receiver = DynamicCast<PacketSink> (gwUsersApps.Get (0));
  Ptr<CbrApplication> sender = DynamicCast<CbrApplication> (utUsersApps.Get (0));
  NS_LOG_INFO ("--- Summary ---");
  NS_LOG_INFO ("  Per sender sent: " << sender->GetSent () << " Bytes.");
  NS_LOG_INFO ("  Number of senders one beam: " <<endUsersPerUt *  utsPerBeam);
  NS_LOG_INFO ("  Total Bytes sent: " <<endUsersPerUt * utsPerBeam * sender->GetSent ()<< " Bytes.");
  NS_LOG_INFO ("  Receiver has received: " << receiver->GetTotalRx () << " Bytes.");
  double throughtput = 0.0;
  throughtput = (receiver->GetTotalRx () * 8) / (appReceiveStopTime.GetSeconds() - appSendStartTime.GetSeconds());
  NS_LOG_INFO ("  Throughtput: " << throughtput << " bps.");

  return 0;
}
`

**Comment by pravenea-cnes** [comment]
Hello,
By running your simulation, I noticed around 20 % loss at receiver, which is not a bad performance if your channel is loaded.
You can check with curves in Annex B of DVB standard to check the MAC load you generate.
I found that in your throughput computation, you divide by appReceiveStopTime (which is 60) while your sources transmit during appSendStopTime (which is 10).
If you look at the global throughput we find 187.5 kbps while you compute 30.9 kbps.

Here is the reference of DVB document :
ETSI TR 101 545-4
Digital Video Broadcasting (DVB);
Second Generation DVB
Interactive Satellite System (DVB-RCS2);
Part 4: Guidelines for Implementation and Use of EN 301 545-2

Regards,

**Comment by sebastianfcs** [comment]
thanks for help 👍 
I have two questions.
if i do not set random access attributes, what is this simulation's default random access?
There is MARSALA random access tech in the Design Documentation, but it seems that i cannot find it in sns3.
thanks a lot :)

**Comment by pravenea-cnes** [comment]
MARSALA is available on dev-cnes branch
