### ISSUE TITLE
Error when running examples

### ISSUE THREAD

**Issue by BurtonYu** [sns3/sns3-satellite#19]
I have downloaded the data, and try to run an example in SNS3, but I get an error. Could you give me some help?

./waf --run contrib/satellite/examples/sat-fwd-system-test

Waf: Entering directory `/home/yutao/WorkSpace/ns-allinone-3.29-satellite/ns-3.29/build'
Waf: Leaving directory `/home/yutao/WorkSpace/ns-allinone-3.29-satellite/ns-3.29/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (9.132s)
msg="Incompatible types. (feed to "c++filt -t" if needed)
got=CallbackImpl<void,ns3::Ptr<ns3::SatBbFrame>>
expected=CallbackImpl<void,ns3::SatEnums::SatBbFrameType_t>", file=./ns3/callback.h, line=1449
file=./ns3/traced-callback.h, line=268
terminate called without an active exception
Command ['/home/yutao/WorkSpace/ns-allinone-3.29-satellite/ns-3.29/build/contrib/satellite/examples/ns3.29-sat-fwd-system-test-optimized'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

**Comment by pravenea-cnes** [comment]
A bugfix has been provided on dev-cnes branch.

**Comment by BurtonYu** [comment]
Thank you a lot for your reply and I have fixed this. But during my simulation, I find this strange phenomenon that under various SINR level, the packet receiving metrics such as throughput and end-to-end delay (including queuing delay) is alway the same. Could you tell me why is this happening?

**Comment by pravenea-cnes** [comment]
I would say that depending on the duration of SINR variations and depth ot these variations, it might not imply a modification of the ModCod used or a variation small enough to limit the impact on throughput and delay.

**Comment by BurtonYu** [comment]
I am using sat-fwd-system-test-example.cc, and transmit power of the satellite is set to 0 dbw and 15 dbw. I think the variations should be large enough. Is it possible that I do not set some system parameters right?

**Comment by pravenea-cnes** [comment]
Which one of these transmit powers do you set to 0 and 15 ? Could you precise if you run a simulation with the power set at 0 then another run at 15 ? Or is it something else ?
ns3::SatGeoFeederPhy::TxMaxPowerDbw
ns3::SatGeoUserPhy::TxMaxPowerDbw
ns3::SatGwPhy::TxMaxPowerDbw
ns3::SatUtPhy::TxMaxPowerDbw

**Comment by BurtonYu** [comment]
I change ns3::SatGeoUserPhy::TxMaxPowerDbw and yes, I run a simulation with the power set at 0 then another run at 15. In order to simulate the queuing delay, I also made the following settings to on-off app：

Ptr<ExponentialRandomVariable> onRv = CreateObject<ExponentialRandomVariable> ();
onRv->SetAttribute ("Mean", DoubleValue (9));
Ptr<ExponentialRandomVariable> offRv = CreateObject<ExponentialRandomVariable> ();
offRv->SetAttribute ("Mean", DoubleValue (1));

Config::SetDefault ("ns3::OnOffApplication::OnTime", PointerValue (onRv));
Config::SetDefault ("ns3::OnOffApplication::OffTime", PointerValue (offRv));

**Comment by pravenea-cnes** [comment]
Maybe you could try with a smaller value for that power (less than zero) and/or increase the transmitting throughput from the source app.

**Comment by BurtonYu** [comment]
I have tried a smaller value of transmit power 10 dbm and 0 dbm, it turn out that the throughput will either be the same value or 0 (All packets can not be decoded). And I also try increase the transmitting rate, the queuing delay is surely increased but still, changing transmit power will not effect the delay and throughput. Maybe you can contact me when you have some new discoveries? Here is my email: 18717831586@163.com. Thank you again for your excellent work.
