### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 1kastner** [sns3/sns3-satellite#2]
Hi there,

first of all thank you very much for sharing the project! I wondered under which license it is distributed?

**Comment by camillem** [comment]
Hi, 
It would be great indeed to clarify it, as some files have a GPL-2 only header and others a GPL-3 or later.

**Comment by dupejb-cnes** [comment]
Hi,
Thanks for raising the issue! As part of ns3 project, sns3 should be GPLv2.

**Comment by 1kastner** [comment]
If I add this to the README.md, would you accept such a pull request, @dupejb-cnes ?

**Comment by dupejb-cnes** [comment]
@1kastner Yes, please do so!

**Comment by dupejb-cnes** [comment]
Hello, I've set a quick indication on Readme for licensing, but pull requests are still welcome.

**Comment by 1kastner** [comment]
perfect, at #4 there it is.
