### ISSUE TITLE
LEO Satellites in SNS3

### ISSUE THREAD

**Issue by FizzaZafar** [sns3/sns3-satellite#20]
Hello,
I am trying to integrate LEO Satellites into the SNS3 module. Can you please tell me why DVB-S2/ RCS2 won't work for it? As far as I have read, there is nothing in the standard definition that prevents it from being used by LEO satellites. I will really appreciate any clarification in this regard.
Thanks!

**Comment by pravenea-cnes** [comment]
Hello,
With LEO satellites, gateways have to deal with satellites handover, which does not occur when you use a geostationnary satellite.
To use DVB-S2/RCS2 in a LEO context, the system will need to define signalisation to deal with LEO particularities. You also need to define if the satellite payload is transparent or regenerative and how to deal with traffic routing.
It is not impossible to use DVB-S2/RC2 with LEO satellites but some designs shall be done.
Feel free to design it and share your developments.

**Comment by FizzaZafar** [comment]
Thank you for the response. I would really appreciate if you could help me a little more.
My basic implementation is as follows:
I have scheduled events that update the position of the satellite to pre-specified longitude, latitude and altitude. Can I expect this event to cascade, seeing as there are mobility observers installed to the ground stations in satellite-helper.cc? 
I am running the predefined simple scenario, with simulation time 50s. There are 2 flows running from user A to B and vice versa, with user A being a UT and user B being behind the GW. I update the longitude and latitude values at 1,2 and 10s into the simulation.

Currently, I am getting the following exception after the last update.
"msg="Starting reception of a packet when receiving DA transmission!", file=../../contrib/satellite/model/satellite-phy-rx-carrier.cc, line=322
terminate called without an active exception"

I will appreciate any help you can provide on this. Thanks!
