### ISSUE TITLE
Adapting SNS3 to LEO Satellites (Follow-up)

### ISSUE THREAD

**Issue by FizzaZafar** [sns3/sns3-satellite#21]
Thank you for the response. I would really appreciate if you could help me a little more.
My basic implementation is as follows:
I have scheduled events that update the position of the satellite to pre-specified longitude, latitude and altitude. Can I expect this event to cascade, seeing as there are mobility observers installed to the ground stations in satellite-helper.cc? 
I am running the predefined simple scenario, with simulation time 50s. There are 2 flows running from user A to B and vice versa, with user A being a UT and user B being behind the GW. I update the longitude and latitude values at 1,2 and 10s into the simulation.

Currently, I am getting the following exception after the last update.
"msg="Starting reception of a packet when receiving DA transmission!", file=../../contrib/satellite/model/satellite-phy-rx-carrier.cc, line=322
terminate called without an active exception"

I will appreciate any help you can provide on this. Thanks!

_Originally posted by @FizzaZafar in https://github.com/sns3/sns3-satellite/issues/20#issuecomment-680880552_

**Comment by pravenea-cnes** [comment]
The mobility observers are here to handle UTs mobility not satellite mobility.

Which file do you use from the example ?
When you run it, is it without modifications or with the satellite mobility events ?

**Comment by FizzaZafar** [comment]
So I would need to implement mobility observer for satellite as well?
I am using my own script that starts 2 tcp flows and schedules the mobility events.

**Comment by pravenea-cnes** [comment]
Yes, satellite mobility is not handled actually.
Have you tried removing the mobility events from your script ? To check if the problem is linked to satellite mobility ?
