### ISSUE TITLE
Error in sat-onoff-example for larger scenario

### ISSUE THREAD

**Issue by vikalp261** [sns3/sns3-satellite#23]
When I tried to run the sat-onoff-example in the dev branch for larger or full scenario, it returned an error. The error was from installtrafficmodel in simulationhelper. 
I intuitively feel that in line 1155 of simulation-helper.cc,
auto app = onOffHelper.Install (gwUsers.Get (i)).Get (0); 
should be replaced with
auto app = onOffHelper.Install (m_gwUserId).Get (0);
With this fix, the larger scenario runs. Can you please confirm if this update is appropriate?

**Comment by pravenea-cnes** [comment]
I confirm that this line should be replaced.
I think there is a typo in your workaround but this is the idea.
Then the line :
`auto app = onOffHelper.Install (gwUsers.Get (i)).Get (0);`
should be replaced by :
`auto app = cbrHelper.Install (gwUsers.Get (m_gwUserId)).Get (0);`

**Comment by vikalp261** [comment]
Thanks.
