### ISSUE TITLE
Rain fading

### ISSUE THREAD

**Issue by wdnmd2** [sns3/sns3-satellite#24]
Hello, I want to know how the rain fading in sns3 is simulated. What model is used? What about those documents?Thanks for your help.

**Comment by pravenea-cnes** [comment]
Hello, if you want to model rain fading, I would suggest to configure the Fading Model as follows :
`Config::SetDefault ("ns3::SatBeamHelper::FadingModel",EnumValue (SatEnums::FADING_TRACE));`

There is an example of use in the sat-trace-input-fading-example.cc example file.

This model uses as input, files for fading values.

Files are provided in the directory {NS-3-root-folder}/contrib/satellite/data/fadingtraces/input
These files are two-columns files. The first column is the Time as double and the second column is the fading value as double.

With this method you can use the model you want for rain attenuation modelization.

**Comment by wdnmd2** [comment]
Thanks for your reply!
