### ISSUE TITLE
A problem about "Suspend:no repository found in satellite"

### ISSUE THREAD

**Issue by zhuangshangyuan** [sns3/sns3-satellite#25]
Hello,sorry to disturb you.I encountered a problem when I run the examples.
After build successfully,the programs in examples will be suspend due to no repository found in contrib/satellite.
Below is the screenshot:
![1](https://user-images.githubusercontent.com/79755783/110729807-4d458000-825a-11eb-85e8-6c9a90e118e9.PNG)
![2](https://user-images.githubusercontent.com/79755783/110729819-52a2ca80-825a-11eb-9e69-00a92247276a.PNG)
Is there any solution to this problem?Looking forward to your reply.Thank you!!!

**Comment by pravenea-cnes** [comment]
Hello,
I could not reproduce this issue.
Have you followed each step of SNS3 install process ?
Could you download the submodule inside satellite ?

Regards

**Comment by yeliqseu** [comment]
I confirm that I see the same issue. I installed SNS3 to a default ns-3.29 installation following the steps.

However, one quick fix to the issue is to create an empty .hg folder in contrib/satellite. After simulation, there will be an empty file: "contrib/satellite/.hg/wcache/checkisexec" created.

**Comment by zhuangshangyuan** [comment]
Thanks for the reply, I have solved this problem.
Thanks very very much.
