### ISSUE TITLE
Does SNS3 support LEO constellation system

### ISSUE THREAD

**Issue by nswdxfm20008** [sns3/sns3-satellite#36]
hello
On one hand, I saw the dev-leo code branch in sns3-satellite repository, on the other hand, in the master branch sgp4 model can be found which is mainly used in leo satellite. so, dose it mean that SNS3 support LEO constellation yet? and what is the relationship between master branch and dev-leo branch?

**Comment by pravenea-cnes** [comment]
Hello,
SNS3 will support LEO satellites. By now, it is only partial support.
The dev-leo branch is mainly for purpose with one satellite while in the master branch, il will be possible to simulate several LEO satellites.

**Comment by nswdxfm20008** [comment]
Thank you for your reply!
I would like to ask further, what are the specific aspects of the currently partially supported LEO capabilities? Is there any version and time plan for SNS3 to eventually support LEO Constellation?
Also, based on your response, the current master branch can already support several LEO satellites, does that mean that further support for the LEO constellation only needs to be based on the current master branch, right?

**Comment by Kniyl** [comment]
Hi,

Support for LEO satellites is not in `master` yet.

LEO satellites and constellations have been added into the `dev` branch and additional support for these features will be added in the upcomming months (consolidation, optimization…).

We are currently in the process of fixing a few remaining issue on the `dev` branch to merge it into `master` and bring LEO support in this default branch.

**Comment by pravenea-cnes** [comment]
This issue is somehow related to issue #41.
We close this issue and centralise the discussion on #41.
