### ISSUE TITLE
Help needed to build satellite module

### ISSUE THREAD

**Issue by Azra-batool** [sns3/sns3-satellite#39]
Hello
I am trying to build satellite module with ns3.39. I changed the wscrip files to CMakeLists.txt and was able to configure the satellite module but when I try to build it using .# /ns3 build -j 9 command, it gives me the following error. 
can you please help me in this case?file:///home/azra/Pictures/Screensh
![Screenshot from 2023-07-17 11-30-59](https://github.com/sns3/sns3-satellite/assets/60134336/ef8c0ced-8ccc-4beb-b805-7ae3d37a6fc4)
ots/Screenshot%20from%202023-07-17%2011-30-46.png
![Screenshot from 2023-07-17 11-31-07](https://github.com/sns3/sns3-satellite/assets/60134336/4d7b8365-5c01-4602-a90e-9b5aa8318586)

**Comment by Kniyl** [comment]
Hi,

It seems like you’re using the master branch with ns-3.39. Unfortunately this branch is not ready yet for this NS3 release, latest supported version is still ns-3.29. You can use the `dev` branch instead which had a number of improvements and specific patches to support modern NS3 versions, up to and including ns-3.39.

Efforts are being put into this `dev` branch to fix a few remaining issues and hopefully merge it into master pretty soon.
