### ISSUE TITLE
Packet Tracing using Pcap in sns-3

### ISSUE THREAD

**Issue by Kilipie** [sns3/sns3-satellite#42]
When I run the example, the result is a log file, Is there any way to replace it with a pcap? 
I didn't find any options related to pcap in satellite-helper or simulator-helper.
Can you give me some advice for this?

**Comment by bastientauran** [comment]
Hello,

Currently there is no way to save traffic in a pcap file, and there are no plans to add this feature in a near future.

Sorry

**Comment by Kilipie** [comment]
Hello
Thank you for replying.
I have one more question. 
Does SNS-3 provide any visualizer? like NetAnim etc.

**Comment by bastientauran** [comment]
Hello,

There is no visualizer in SNS-3 neither, sorry.

**Comment by Kilipie** [comment]
Thank you for replying it.
