### ISSUE TITLE
how to execute an example in ns3? 

### ISSUE THREAD

**Issue by meimous** [sns3/sns3-satellite#5]
hi,
i installed SNS3 as u said in the instructions using waf.
when i want to execute any example i have this error

./waf --run contrib/satellite/examples/sat-training-example

ns-3.29/build/contrib/satellite/examples/ns3.29-sat-training-example-optimized: error while loading shared libraries: libns3.29-satellite-optimized.so: cannot open shared object file: No such file or directory
Command ['/home/bada/Desktop/satellite/ns-3.29/build/contrib/satellite/examples/ns3.29-sat-training-example-optimized'] exited with code 127

please help me :(

**Comment by pravenea-cnes** [comment]
Hello,

I noticed that the README was not updated concerning the post-compilation part.
The README has been updated and, by following the steps of installation, the examples run.

Could you please indicate if the problem still remains or if the instructions update solved it ?

Thanks

**Comment by badnava-babak** [comment]
This problem still exists, and I couldn't run the example. I believe my problem is with the post-compilation part. I cannot update the submodules. every time, it takes a lot of time and fails in the end.
