### ISSUE TITLE
SNS3 Documentation

### ISSUE THREAD

**Issue by ddalai** [sns3/sns3-satellite#7]
Where will I get the documentation about SNS3?

**Comment by dupejb-cnes** [comment]
Hello!
Documentation is available the same way as ns3 : through sphinx and doxygen. We will soon put the html doc on sns3.org, but you can already build it with the ./waf doc command.

**Comment by ddalai** [comment]
Thanks for the help

**Comment by dupejb-cnes** [comment]
No problem, I am closing the issue
