### ISSUE TITLE
After Integration of SNS3 with NS3

### ISSUE THREAD

**Issue by ddalai** [sns3/sns3-satellite#8]
Dear Admin,

                 I tried to execute basic example programs of NS3(like first.cc) in SNS3 with command ./waf --run scratch/first but after compiling the program simulation is not starting. But before integrating satellite module it was working fine. After the satellite module integration, I cloned the data as per instruction is given and after that, I build in NS3. Some satellite program examples(As per given) is compiling perfectly with simulation and some are not showing simulation(But compiling with no error). Can you identify what might be the problem in my case? Please help.

**Comment by dupejb-cnes** [comment]
Hi, 
Can you please specify which example programs you tired to run? Are they related to the satellite module?

**Comment by ddalai** [comment]
I tried examples of both satellite module and normal NS3 program. 
1. First I tried sat-trace-input-rx-power-example.cc and which was working fine and showed the simulation results.
2. Then I tried sat-tutorial-example.cc where it complied satellite modules after that it showed 
"Waf: Leaving directory `/home/deba/NS3repo/ns-3-allinone/ns-3-dev/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (1m22.979s)" 
this message and finished simulation without any result. 
3. Then I tried a normal NS3 program called first.cc which showed like explained in point 2. 
4. I tried some other satellite module program like sat-training-example.cc but showing similar results like

"~/NS3repo/ns-3-allinone/ns-3-dev$ ./waf --run scratch/sat-training-example
Waf: Entering directory `/home/deba/NS3repo/ns-3-allinone/ns-3-dev/build'
[   1/3159] Compiling install-ns3-header: ns3/traffic-time-tag.h
[   2/3159] Compiling install-ns3-header: ns3/traffic-time-tag.h
[3103/3159] Compiling scratch/sat-training-example.cc
[3104/3159] Compiling scratch/subdir/scratch-simulator-subdir.cc
[3105/3159] Compiling scratch/scratch-simulator.cc
[3114/3159] Linking build/scratch/subdir/subdir
[3115/3159] Linking build/scratch/scratch-simulator
[3117/3159] Linking build/scratch/sat-training-example
Waf: Leaving directory `/home/deba/NS3repo/ns-3-allinone/ns-3-dev/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (49.063s)
"

**Comment by dupejb-cnes** [comment]
Have you tried to look in the data/sims repository? This is where the stats are stored by default. Also, by default, ns3 does not output any information on stdout.

**Comment by ddalai** [comment]
Thank you. Yes, I got the simulation results in data/sims repository.  Can you tell the code by which I can store simulation data for normal NS3 codes?  
"auto simulationHelper = CreateObject<SimulationHelper> ("example-tutorial");" Is this code is sufficient to collect the simulation results?

**Comment by linhgiangece** [comment]
Hi, I tried to install the sns3 satellite module with version 3.35 but got this error. Could anyone please help me fix this? Thanks so much. 
<img width="659" alt="Screenshot 2024-12-11 143405" src="https://github.com/user-attachments/assets/e984f6df-33db-418a-8d3e-4d16947222b1">

**Comment by ddalai** [comment]
I apologise. I stopped using NS-3 long back. I am not aware of this issue.

*_____________________________________________________________*
*Sincerely,*

*Debabrata Dalai <https://www.linkedin.com/in/debabrata-dalai-a88b6486/>,*
*Senior Research Scholar,*
*IEEE IIST SB chair,  Avionics,*
*Systems and Networks Lab <https://iist-sysnet.github.io/>, IIST
<https://www.iist.ac.in/>*
