### ISSUE TITLE
Trying to allocate twice the same uid: ns3::TrafficTimeTag

### ISSUE THREAD

**Issue by WalkerLYU** [sns3/sns3-satellite#9]
Hi,

I installed SNS3 and integrated the two modules traffic and stats. The message "Trying to allocate twice the same uid: ns3::TrafficTimeTag" appeared after running first.cc in scratch. I found that the class named TrafficTimeTag existed in traffic/model/ and stats/model, which may cause the problem. How to solve it?

Thanks,
Lyu

**Comment by WalkerLYU** [comment]
This problem was solved by changing OS from macOS to Ubuntu Linux, but compiling remains failed in macOS.

**Comment by dupejb-cnes** [comment]
Thank you for your feedback! We are aware there is a conflict for traffic-time-tag, but it should not be an issue for building - at least on ubuntu it seems.
